export type ContentSection = {
  title: string;
  paragraphs: string[];
  bullets?: string[];
  links?: { label: string; href: string }[];
};

export type ContentPage = {
  label: string;
  title: string;
  description: string;
  intro: string;
  updated: string;
  notice?: string;
  sections: ContentSection[];
};

const updated = "17 July 2026";
const contactEmail = "goldensparkbh@gmail.com";

export const contentPages: Record<string, ContentPage> = {
  about: {
    label: "About Fikra in Action",
    title: "Practical technology. Clear recommendations.",
    description: "Learn about Fikra in Action, our purpose, how the platform is funded, and how we create practical technology guidance.",
    intro: "Fikra in Action is a Golden Spark Consultancy project that helps people discover, understand, and compare AI tools, software, digital products, and online services without exaggerated claims or unnecessary complexity.",
    updated,
    sections: [
      { title: "Our purpose", paragraphs: ["Technology should help people complete meaningful work—not create another layer of confusion. Our purpose is to turn product information into practical guidance: what a tool does, who it suits, what it costs, where it may fall short, and what a reader should verify before making a decision."] },
      { title: "Who we write for", paragraphs: ["Our content is designed for founders, professionals, creators, small businesses, teams, students, and anyone evaluating digital tools. We aim to explain products clearly enough for a first-time buyer while retaining the detail needed for a considered business decision."] },
      { title: "What we publish", paragraphs: ["Fikra in Action publishes product overviews, independent reviews, comparisons, alternatives, tutorials, practical guides, and verified deal information."], bullets: ["Reviews explain advantages, limitations, pricing, audience fit, and points that require confirmation.", "Comparisons focus on decision factors rather than the longest feature list.", "Tutorials focus on a repeatable outcome and identify prerequisites or limitations.", "Deals are published only when the offer and relevant conditions can be verified."] },
      { title: "How we create content", paragraphs: ["We combine official product information, structured research, direct product evaluation where available, reliable third-party evidence, and human editorial review. Drafting tools may help organize information or produce an initial structure, but a human editor remains responsible for checking claims, disclosures, links, images, and the final recommendation before publication."], links: [{ label: "Read our editorial policy", href: "/editorial-policy" }, { label: "See our review methodology", href: "/review-methodology" }] },
      { title: "How the platform is funded", paragraphs: ["Some links are affiliate links. If a reader purchases or registers through one of those links, Fikra in Action may receive a commission at no additional cost to the reader. Affiliate income supports research, publishing, hosting, and continued development of the platform. It does not purchase a positive review, rating, or recommendation."], links: [{ label: "Read the full affiliate disclosure", href: "/affiliate-disclosure" }] },
      { title: "Accountability", paragraphs: ["Products, prices, and terms change. We identify information that may change, review important pages, and correct material errors when they are found. Readers and product providers are welcome to submit a correction with a reliable supporting source."], links: [{ label: "Contact Fikra in Action", href: "/contact" }] },
    ],
  },
  "editorial-policy": {
    label: "Editorial standards",
    title: "Useful, balanced, and accountable content.",
    description: "The editorial standards governing research, AI assistance, commercial relationships, corrections, and publication on Fikra in Action.",
    intro: "Our editorial process is designed to help readers make informed decisions—not simply encourage clicks. This policy applies to reviews, comparisons, tutorials, guides, deals, and generated landing pages published by Fikra in Action.",
    updated,
    sections: [
      { title: "Editorial principles", paragraphs: ["Every published page should be useful, understandable, evidence-aware, and transparent about relevant commercial relationships."], bullets: ["Accuracy: factual claims should be supported by a reliable source or direct observation.", "Clarity: important limitations, conditions, and uncertainty should be easy to understand.", "Balance: relevant disadvantages and better-fit alternatives should not be hidden.", "Independence: compensation does not determine our conclusions or ratings.", "Accountability: material errors should be corrected promptly."] },
      { title: "Research and sources", paragraphs: ["We prefer official product documentation, pricing pages, release notes, provider policies, demonstrations, and direct testing. Reliable independent sources may be used for context or verification. Customer reviews can help identify issues to investigate, but isolated comments are not treated as established fact."], bullets: ["We distinguish provider claims from our own observations.", "We avoid presenting estimates or changing prices as permanent facts.", "We do not knowingly publish fabricated testimonials, ratings, statistics, or product capabilities."] },
      { title: "Hands-on testing and experience", paragraphs: ["We state or imply hands-on experience only when the product or relevant feature has actually been accessed. When a page is based primarily on documented research rather than full testing, the wording should reflect that limitation. Access to a free trial, review account, demonstration, or complimentary product does not guarantee favourable coverage."] },
      { title: "Use of AI and automation", paragraphs: ["AI-assisted tools may help structure a draft, summarize supplied information, suggest headings, or improve clarity. They are not treated as authoritative sources. Generated claims, prices, comparisons, images, and citations must be reviewed before publication."], bullets: ["A human editor is responsible for the published page.", "Unverified statements are removed, qualified, or clearly marked for confirmation.", "AI assistance cannot be used to invent testing, expertise, testimonials, or results.", "Material conflicts and affiliate relationships must still be disclosed."] },
      { title: "Images and visual material", paragraphs: ["Product images may be retrieved from an official product website or provided through a media library. Source attribution is included where appropriate. Images are reviewed for relevance and should not be presented in a way that falsely implies ownership, endorsement, or a feature that the product does not provide. Rights holders may contact us about removal or correction."] },
      { title: "Commercial relationships", paragraphs: ["Affiliate agreements, sponsorships, free access, gifts, or other material relationships do not entitle a provider to control our conclusions. A relevant relationship is disclosed clearly on the content where readers encounter the recommendation or link. Sponsored content, if accepted, is labelled separately and is not presented as an independent review."], links: [{ label: "Affiliate disclosure", href: "/affiliate-disclosure" }] },
      { title: "Ratings and recommendations", paragraphs: ["Ratings reflect the evaluation criteria described in our review methodology. They are editorial judgments, not scientific measurements or guarantees. A high rating does not mean a product is appropriate for every reader, and a lower rating does not mean it has no useful audience."], links: [{ label: "Review methodology", href: "/review-methodology" }] },
      { title: "Publication and review", paragraphs: ["Before publication, content should be reviewed for factual consistency, working links, appropriate disclosures, readable structure, and unsupported claims. Material pages may be updated when pricing, product functionality, ownership, availability, or our evaluation changes. The displayed update date refers to the most recent meaningful editorial review, not necessarily a minor spelling correction."] },
      { title: "Corrections", paragraphs: ["When a material error is confirmed, we correct it as soon as reasonably possible. Depending on the issue, we may amend the wording, remove a claim, update a rating, replace an image, or unpublish the page while it is reviewed. Correction requests should identify the page, disputed statement, and a reliable supporting source."], links: [{ label: "Submit a correction", href: `mailto:${contactEmail}?subject=Correction%20request%20-%20Fikra%20in%20Action` }] },
      { title: "Editorial complaints", paragraphs: ["Questions about fairness, disclosure, conflicts, or the application of this policy may be sent to our contact email. Commercial disagreement by itself is not a reason to remove accurate, responsibly presented criticism."], links: [{ label: contactEmail, href: `mailto:${contactEmail}` }] },
    ],
  },
  "review-methodology": {
    label: "How we evaluate",
    title: "A practical review methodology.",
    description: "How Fikra in Action researches, tests, scores, compares, updates, and discloses commercial relationships in product reviews.",
    intro: "We focus on the factors that determine whether a tool remains useful after the demonstration ends. The exact weight of each factor varies by product category and intended audience.",
    updated,
    sections: [
      { title: "1. Define the product and audience", paragraphs: ["We begin by identifying the problem the product claims to solve, its main product category, intended user, supported platforms, important regional restrictions, and the realistic alternatives a buyer might consider."] },
      { title: "2. Gather evidence", paragraphs: ["Research normally begins with the provider's official product pages, documentation, pricing, terms, release notes, and support material. Where useful, we add direct testing, demonstrations, reputable independent research, and recurring user issues that can be verified."] },
      { title: "3. Test the real workflow", paragraphs: ["When access is available, we evaluate the product using a realistic task rather than relying only on a prepared demonstration. We consider setup effort, navigation, output quality, reliability, collaboration, integrations, export options, support, and the effort required to obtain repeatable value. If meaningful hands-on testing was not completed, the review should not claim that it was."] },
      { title: "4. Evaluate decision factors", paragraphs: ["The following factors guide the review. Not every category is equally important for every product."], bullets: ["Purpose and workflow fit: whether the product solves the stated problem for the intended audience.", "Usability and adoption: setup, learning curve, accessibility, and day-to-day clarity.", "Capabilities and output quality: whether core features work reliably and produce useful results.", "Pricing and value: total likely cost, plan limits, required seats, usage allowances, and switching cost.", "Integrations and portability: compatibility, export, APIs, and risk of lock-in.", "Trust and control: privacy information, security controls, permissions, transparency, and administrative options.", "Support and maturity: documentation, customer support, reliability, update history, and known limitations.", "Regional fit: language, billing, availability, support hours, and features that differ by location."] },
      { title: "5. Rating scale", paragraphs: ["When a numerical rating is used, it summarizes the complete editorial assessment for the stated audience."], bullets: ["4.5–5.0: exceptional fit with strong execution and limited material weaknesses.", "4.0–4.4: very good for the intended audience, with manageable limitations.", "3.5–3.9: useful and competitive, but important trade-offs should be considered.", "3.0–3.4: adequate for specific needs; alternatives may offer better overall value.", "Below 3.0: significant limitations reduce our ability to recommend it broadly."] },
      { title: "6. Pricing and availability", paragraphs: ["Prices, promotions, features, and regional availability can change without notice. We record the date or context of price information where practical and direct readers to the provider for current billing terms. Starting prices are not treated as the likely total cost when required seats, limits, add-ons, or usage charges materially affect the decision."] },
      { title: "7. Comparisons and alternatives", paragraphs: ["Products are compared using common decision factors and a defined use case. The winner may differ by audience. We avoid declaring a universal winner when the evidence supports different choices for different workflows."] },
      { title: "8. Affiliate and provider relationships", paragraphs: ["Affiliate availability does not determine whether a product is included or how it is rated. If we can earn a commission, the relationship is disclosed near the recommendation or affiliate link. Complimentary access, sponsorship, or other material support must also be disclosed when relevant."], links: [{ label: "Affiliate disclosure", href: "/affiliate-disclosure" }] },
      { title: "9. AI-assisted drafting", paragraphs: ["AI may assist with organizing supplied facts or producing a structured draft. It does not replace source verification, direct testing, conflict disclosure, or human judgment. Automatically retrieved product images are reviewed and attributed where appropriate before publication."] },
      { title: "10. Updates and corrections", paragraphs: ["Products evolve, so important reviews are reassessed when significant changes are identified. We may update facts, conclusions, scores, screenshots, links, or recommended alternatives. Readers and providers can report a material error; evidence is reviewed under the same standards regardless of commercial relationship."], links: [{ label: "Submit a correction", href: "/contact" }] },
    ],
  },
  contact: {
    label: "Get in touch",
    title: "Contact Fikra in Action.",
    description: "Contact Fikra in Action about corrections, product suggestions, privacy requests, affiliate programmes, or commercial enquiries.",
    intro: "Send a correction, suggest a tool, ask about our editorial process, or discuss a relevant commercial opportunity. Please choose a clear subject line and include the information needed for us to understand your request.",
    updated,
    notice: `Primary contact: ${contactEmail}`,
    sections: [
      { title: "General enquiries", paragraphs: ["For general questions about Fikra in Action, the platform, or its content, email us using the address below."], links: [{ label: contactEmail, href: `mailto:${contactEmail}?subject=Fikra%20in%20Action%20enquiry` }] },
      { title: "Corrections", paragraphs: ["To report an inaccurate price, feature, link, statement, or image, include the exact page URL, the information you believe is incorrect, the proposed correction, and a reliable supporting source. We review evidence independently and do not accept payment to remove accurate criticism."], links: [{ label: "Submit a correction", href: `mailto:${contactEmail}?subject=Correction%20request%20-%20Fikra%20in%20Action` }] },
      { title: "Product suggestions", paragraphs: ["You may suggest a tool, service, course, or digital product for possible coverage. Include the official website, product category, intended audience, pricing information, and why it may be useful to readers. A suggestion does not guarantee coverage or a positive review."], links: [{ label: "Suggest a product", href: `mailto:${contactEmail}?subject=Product%20suggestion%20-%20Fikra%20in%20Action` }] },
      { title: "Affiliate and commercial enquiries", paragraphs: ["Relevant affiliate programmes, sponsorship proposals, and partnership enquiries may be submitted for consideration. Commercial arrangements cannot purchase a favourable rating, conclusion, or undisclosed placement. Sponsored material must be identified clearly."], links: [{ label: "Commercial enquiry", href: `mailto:${contactEmail}?subject=Commercial%20enquiry%20-%20Fikra%20in%20Action` }] },
      { title: "Privacy requests", paragraphs: ["To request access, correction, deletion, restriction, objection, or withdrawal of consent in relation to personal data, use the subject line “Privacy request”. We may need reasonable information to confirm identity and locate the relevant data before responding."], links: [{ label: "Submit a privacy request", href: `mailto:${contactEmail}?subject=Privacy%20request%20-%20Fikra%20in%20Action` }, { label: "Read the privacy policy", href: "/privacy" }] },
      { title: "Response and third-party support", paragraphs: ["We aim to acknowledge substantive enquiries within five business days, although complex requests may take longer. Fikra in Action is not the support provider for products reviewed on the site. Billing, cancellation, account access, refunds, and technical-support requests should be directed to the relevant product provider."] },
    ],
  },
  "affiliate-disclosure": {
    label: "Transparency",
    title: "Affiliate disclosure.",
    description: "How affiliate links, commissions, sponsored relationships, tracking, and editorial independence work on Fikra in Action.",
    intro: "Some links on Fikra in Action are affiliate links. If you click one of these links and purchase, subscribe, or register, we may receive a commission or referral benefit. This disclosure explains what that means for readers and for our editorial work.",
    updated,
    notice: "Using an affiliate link normally does not increase the price you pay. The provider controls its own pricing, eligibility, and terms.",
    sections: [
      { title: "What is an affiliate link?", paragraphs: ["An affiliate link contains information that allows a provider or affiliate network to recognize that a visitor was referred by Fikra in Action. A qualifying action may result in a commission, fixed referral fee, credit, or another disclosed benefit."] },
      { title: "Where affiliate links appear", paragraphs: ["Affiliate links may appear in reviews, comparisons, tutorials, deal pages, directories, buttons, or other recommendations. Fikra in Action may use a short internal redirect such as /go/product-name before sending the visitor to the provider. This supports link management and click measurement."] },
      { title: "How we disclose the relationship", paragraphs: ["Pages containing affiliate recommendations include a plain-language disclosure near the relevant content or call to action. A link to this full policy provides additional detail but does not replace the page-level disclosure. Link attributes such as “sponsored” and “nofollow” may also be used, but technical labels alone are not treated as sufficient notice to readers."] },
      { title: "No additional charge from us", paragraphs: ["Fikra in Action does not add a separate charge when you use an affiliate link. The provider may offer the same price, a special offer, or different terms depending on its programme. Always review the final price, renewal terms, taxes, currency, cancellation conditions, and refund policy on the provider's website before completing a transaction."] },
      { title: "Editorial independence", paragraphs: ["Affiliate participation does not guarantee coverage, a positive conclusion, a particular score, or preferred placement. We aim to apply the same research and evaluation standards whether or not an affiliate programme is available. A product may be recommended without an affiliate relationship, and an affiliate product may receive criticism or no recommendation."] },
      { title: "Other material relationships", paragraphs: ["If a provider pays for sponsored content, supplies significant free access, provides a gift, or has another relationship that could reasonably affect how readers assess the content, that relationship should be disclosed. Sponsored content, if published, is labelled and is not presented as an independent review."] },
      { title: "Affiliate click information", paragraphs: ["When an internal affiliate redirect is used, the platform may record the product identifier, destination, referring page, campaign or button position, and time of the click in Firestore. This information is used to operate links, understand aggregate performance, and detect problems. We do not intentionally store payment-card details or the contents of a purchase through the redirect."], links: [{ label: "Privacy policy", href: "/privacy" }, { label: "Cookie policy", href: "/cookies" }] },
      { title: "Third-party responsibility", paragraphs: ["After leaving Fikra in Action, the provider or affiliate network controls its website, checkout, account, cookies, privacy practices, product delivery, billing, and support. Fikra in Action is not a party to the transaction unless expressly stated otherwise."] },
      { title: "Questions", paragraphs: ["If you believe a commercial relationship has not been disclosed clearly, contact us with the page URL and details so we can review it."], links: [{ label: contactEmail, href: `mailto:${contactEmail}?subject=Affiliate%20disclosure%20question` }] },
    ],
  },
  privacy: {
    label: "Legal",
    title: "Privacy policy.",
    description: "How Fikra in Action collects, uses, shares, protects, and retains personal data, including Firebase and affiliate-click information.",
    intro: "This Privacy Policy explains how Fikra in Action handles personal data when you visit the website, use an affiliate link, contact us, or access the private administration area. We aim to collect only information reasonably needed to operate, secure, improve, and understand the platform.",
    updated,
    notice: `Privacy contact: ${contactEmail}. Fikra in Action is a Golden Spark Consultancy project based in the Kingdom of Bahrain.`,
    sections: [
      { title: "1. Scope and applicable principles", paragraphs: ["This policy applies to Fikra in Action pages and services that link to it. It does not govern third-party product providers, affiliate networks, or websites reached through external links. Our handling of personal data is intended to reflect applicable requirements, including Bahrain's Personal Data Protection Law, Law No. 30 of 2018, where it applies."] },
      { title: "2. Information you provide", paragraphs: ["We may receive information you choose to provide when you email us, submit a correction, make a privacy request, propose a product, or communicate about an editorial or commercial matter."], bullets: ["Name, email address, organization, and contact details included in your message.", "The content of your request, attachments, supporting sources, and correspondence history.", "Information reasonably required to verify identity when handling a data-rights request.", "For authorized administrators only, email address and authentication information processed through Firebase Authentication."] },
      { title: "3. Information collected through use", paragraphs: ["The website and its infrastructure may generate technical and usage information needed for delivery, security, diagnostics, and measurement."], bullets: ["Hosting and security logs, which may include IP address, device or browser information, requested URL, timestamps, and error details as processed by our hosting and infrastructure providers.", "Affiliate redirect records, which may include product identifier, destination URL, referring page, campaign, link position, and click time.", "Administrative content records, revisions, product entries, blog posts, and media metadata created by authorized administrators.", "Cookie, local-storage, or similar information described in our Cookie Policy."] },
      { title: "4. Information we do not intentionally collect", paragraphs: ["Fikra in Action does not intentionally collect payment-card details, bank credentials, or the contents of purchases made on a third-party provider's website. We do not intentionally request sensitive personal data through public website pages. Please do not send unnecessary identity documents, financial information, health data, or other sensitive material by email."] },
      { title: "5. How we use information", paragraphs: ["Information may be used for the following purposes."], bullets: ["Provide, host, secure, troubleshoot, and maintain the website.", "Authenticate and authorize administrators.", "Respond to enquiries, corrections, complaints, and privacy requests.", "Manage products, content, media, revisions, and affiliate destinations.", "Measure aggregate affiliate-link activity and diagnose broken or abusive traffic.", "Improve editorial coverage, navigation, performance, and reader experience.", "Comply with applicable law, enforce terms, and protect rights, safety, and security."] },
      { title: "6. Legal grounds", paragraphs: ["Depending on the context and applicable law, processing may be based on consent, steps requested before entering an arrangement, performance of an agreement, compliance with a legal obligation, or legitimate interests such as operating and securing the site, responding to correspondence, maintaining records, and understanding aggregate link performance. Where consent is the basis, it may be withdrawn for future processing, subject to legal or operational limitations."] },
      { title: "7. Service providers and sharing", paragraphs: ["We may share information with service providers that process it on our behalf or support the platform. These may include Firebase and Google Cloud services for hosting, Firestore, Storage, Authentication, logging, and infrastructure; source-control and deployment providers; email providers; and tools used for product-image metadata retrieval. Providers process data under their own contractual and legal obligations."], bullets: ["We may disclose information when required by law, court order, or a competent authority.", "Information may be disclosed to protect the platform, users, or others from fraud, abuse, security threats, or unlawful activity.", "If the project or relevant assets are reorganized or transferred, information may be included subject to appropriate safeguards and notice where required.", "We do not sell payment information or contact lists. We do not disclose personal data to an advertiser merely because it wants to identify a reader."] },
      { title: "8. Affiliate providers and external sites", paragraphs: ["When you follow an external or affiliate link, the receiving provider may collect information under its own privacy and cookie policies. The destination may recognize affiliate parameters or set its own cookies. Review the provider's notices before creating an account or making a purchase. Fikra in Action does not control how an independent destination processes your data."] },
      { title: "9. International processing", paragraphs: ["Cloud, hosting, email, and affiliate services may process information in countries outside Bahrain or the country where you live. Where required, we seek to use providers and transfer mechanisms offering appropriate protections. Laws and government-access rules may differ between countries."] },
      { title: "10. Retention", paragraphs: ["We retain information only for as long as reasonably necessary for the purpose collected, including legal, security, dispute, and record-keeping needs."], bullets: ["General correspondence is normally reviewed for deletion when it is no longer needed.", "Affiliate click records are generally retained for operational and performance analysis for up to 24 months, unless a shorter period is appropriate or longer retention is required for security, disputes, or law.", "Published content, revision history, and administrative audit information may be retained while the content remains active and for a reasonable archive period afterward.", "Backups and provider logs may remain for limited technical retention periods before deletion or overwrite."] },
      { title: "11. Security", paragraphs: ["We use access controls, authenticated administration routes, server-side authorization, restricted database rules, secure hosting, and reasonable operational safeguards. No transmission, storage system, or online service can be guaranteed completely secure. If you believe the platform or your information has been compromised, contact us promptly."] },
      { title: "12. Your choices and rights", paragraphs: ["Subject to applicable law and relevant exceptions, you may request information about processing and seek access, correction, updating, deletion or erasure, blocking or restriction, objection, or withdrawal of consent. You may also ask about recipients or the source of information where applicable. We may request reasonable verification and may retain information when required by law or necessary for legal claims."], links: [{ label: "Submit a privacy request", href: `mailto:${contactEmail}?subject=Privacy%20request%20-%20Fikra%20in%20Action` }, { label: "Bahrain Personal Data Protection Authority", href: "https://www.pdp.gov.bh/" }] },
      { title: "13. Children", paragraphs: ["Fikra in Action is a general technology-information service and is not designed to collect personal data from young children. If you are a parent or guardian and believe a child has provided personal data without appropriate authorization, contact us so the matter can be reviewed."] },
      { title: "14. Changes and contact", paragraphs: ["We may update this policy when the platform, providers, or legal requirements change. The revision date appears at the top of the page. Material changes may receive additional notice where appropriate. Questions, complaints, and rights requests may be sent to the privacy contact below."], links: [{ label: contactEmail, href: `mailto:${contactEmail}?subject=Privacy%20enquiry%20-%20Fikra%20in%20Action` }] },
    ],
  },
  terms: {
    label: "Legal",
    title: "Terms of Service.",
    description: "The terms governing access to and use of Fikra in Action, including content, affiliate links, third-party services, and liability.",
    intro: "These Terms of Service govern your access to and use of the Fikra in Action website and its public content. By using the website, you agree to these Terms. If you do not agree, please stop using the website.",
    updated,
    notice: "Fikra in Action provides general informational and editorial content. It is not the seller, licensor, or support provider for third-party products unless expressly stated.",
    sections: [
      { title: "1. About the service", paragraphs: ["Fikra in Action is a Golden Spark Consultancy project based in the Kingdom of Bahrain. The website publishes reviews, comparisons, tutorials, guides, directories, generated landing pages, and related information about technology products and services."] },
      { title: "2. Eligibility and acceptance", paragraphs: ["You may use the public website only if you can lawfully agree to these Terms in your jurisdiction. If you use the website for an organization, you represent that you are authorized to act for it. The private administration route is restricted to expressly authorized administrators."] },
      { title: "3. Informational purpose", paragraphs: ["Content is provided for general information and decision support. It is not legal, financial, medical, cybersecurity, investment, or other regulated professional advice. You remain responsible for assessing whether a product is appropriate for your needs, data, budget, location, and obligations."] },
      { title: "4. Product information and changes", paragraphs: ["We aim for accurate, useful content, but products, features, prices, exchange rates, promotions, availability, support, ownership, and terms may change without notice. Confirm material information directly with the provider before relying on it or completing a transaction. A publication or update date does not guarantee that every linked provider has remained unchanged."] },
      { title: "5. Reviews, ratings, and results", paragraphs: ["Reviews, ratings, comparisons, and recommendations reflect editorial judgment for a stated audience and time. They are not guarantees of quality, availability, savings, earnings, productivity, compatibility, or any particular result. Individual needs and outcomes vary."] },
      { title: "6. Affiliate links and sponsored relationships", paragraphs: ["Some links may generate a commission or referral benefit for Fikra in Action. Relevant relationships are disclosed in accordance with our Affiliate Disclosure. Compensation does not create a contract between you and Fikra in Action for the third-party product."], links: [{ label: "Affiliate disclosure", href: "/affiliate-disclosure" }] },
      { title: "7. Third-party websites and transactions", paragraphs: ["External links are provided for information or convenience. Third-party providers control their websites, accounts, checkout, cookies, privacy, accessibility, products, licences, billing, renewals, cancellation, refunds, warranties, security, delivery, and support. Your transaction or agreement is with the provider, not Fikra in Action, unless expressly stated otherwise. We are not responsible for independent third-party content or conduct."] },
      { title: "8. Acceptable use", paragraphs: ["You must not misuse the website or interfere with its operation."], bullets: ["Do not attempt unauthorized access to /admin, APIs, databases, storage, accounts, or infrastructure.", "Do not introduce malware, exploit vulnerabilities, overwhelm services, scrape at a rate that disrupts the platform, or bypass technical restrictions.", "Do not use the website to violate law, infringe rights, impersonate another person, or transmit deceptive or harmful material.", "Do not manipulate affiliate tracking, clicks, campaigns, ratings, or site measurements through automated or fraudulent activity.", "Do not reproduce or republish substantial content in a way that substitutes for the website without permission."] },
      { title: "9. Intellectual property", paragraphs: ["The Fikra in Action name, original text, site design, selection, organization, and other original materials are protected by applicable intellectual-property laws. You may view, link to, and make reasonable personal or internal business use of public content. Any broader reproduction, adaptation, resale, systematic extraction, or commercial republication requires prior written permission unless permitted by law."], bullets: ["Product names, logos, screenshots, and trademarks belong to their respective owners.", "Reference to a provider does not imply that it sponsors or endorses Fikra in Action.", "If you believe material infringes your rights, send the exact URL, identification of the work, basis of the claim, and contact information."] },
      { title: "10. Communications and submissions", paragraphs: ["If you send a correction, suggestion, or other submission, you confirm that you have the right to share it and that it is not knowingly false, unlawful, confidential without authorization, or infringing. You permit us to use the submission to evaluate, correct, or improve content. We do not promise to publish suggestions or maintain unsolicited material in confidence."] },
      { title: "11. Privacy and cookies", paragraphs: ["Use of the website is also subject to the Privacy Policy and Cookie Policy, which explain relevant data and technology practices."], links: [{ label: "Privacy policy", href: "/privacy" }, { label: "Cookie policy", href: "/cookies" }] },
      { title: "12. Availability and changes", paragraphs: ["We may change, suspend, restrict, or discontinue any feature or content; correct an error; block abusive traffic; or modify these Terms. We do not guarantee uninterrupted, error-free, or permanently available service. Where reasonable, the current version of these Terms will remain accessible on this page."] },
      { title: "13. Disclaimer of warranties", paragraphs: ["To the maximum extent permitted by applicable law, the website and content are provided “as is” and “as available”. Fikra in Action disclaims implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, availability, and compatibility to the extent those warranties may lawfully be excluded. Nothing in these Terms excludes a right that cannot legally be excluded."] },
      { title: "14. Limitation of liability", paragraphs: ["To the maximum extent permitted by applicable law, Fikra in Action, Golden Spark Consultancy, and their personnel will not be liable for indirect, incidental, special, consequential, exemplary, or punitive loss; lost profits, revenue, data, opportunity, goodwill, or business interruption; or loss arising from a third-party product, external site, pricing change, purchase, account, or provider conduct. Any liability that cannot be excluded will be limited only to the extent permitted by law."] },
      { title: "15. Governing law and disputes", paragraphs: ["These Terms are governed by the laws of the Kingdom of Bahrain, without prejudice to mandatory consumer or data-protection rights that apply in your place of residence. Subject to any mandatory rule, disputes relating to these Terms or the website are submitted to the competent courts of the Kingdom of Bahrain. Before formal proceedings, the parties are encouraged to attempt a good-faith resolution through written notice."] },
      { title: "16. General provisions and contact", paragraphs: ["If a provision is held invalid or unenforceable, the remaining provisions continue in effect and the affected provision is limited to the minimum extent necessary. A failure to enforce a provision is not a waiver. These Terms, together with the policies expressly incorporated, form the agreement governing public use of the website. Questions may be sent to the contact below."], links: [{ label: contactEmail, href: `mailto:${contactEmail}?subject=Terms%20of%20Service%20enquiry` }] },
    ],
  },
  cookies: {
    label: "Legal",
    title: "Cookie policy.",
    description: "How Fikra in Action uses cookies, browser storage, affiliate redirects, and related technologies.",
    intro: "This Cookie Policy explains how Fikra in Action uses cookies, browser storage, and similar technologies. It should be read with our Privacy Policy. The current public website does not intentionally place advertising or behavioural-marketing cookies of its own.",
    updated,
    notice: "Affiliate click measurement on Fikra in Action is performed through server-recorded redirect information and does not, by itself, require us to place a public-user advertising cookie.",
    sections: [
      { title: "1. What are cookies and similar technologies?", paragraphs: ["Cookies are small text files stored by a website in a browser. Similar technologies include local storage, session storage, pixels, SDK identifiers, and server-side records. They can support security, preferences, authentication, measurement, and advertising."] },
      { title: "2. Technologies currently used", paragraphs: ["The platform uses hosting and security infrastructure needed to deliver the website. The private /admin route uses Firebase Authentication and may use browser storage or related technologies to maintain an authorized administrator session. Public visitors do not need an account to read the site."], bullets: ["Essential and security technology: delivery, abuse prevention, reliability, and diagnostics.", "Administrator authentication: sign-in state and secure access to management features.", "Server-side affiliate records: product, destination, referrer, campaign, position, and click time may be recorded when a /go/ link is used.", "Media and embedded resources: externally hosted product images may cause the browser to contact the image host, subject to that host's practices."] },
      { title: "3. Analytics and marketing", paragraphs: ["Fikra in Action does not currently state that it uses a public behavioural-advertising cookie or a public profiling cookie. If optional analytics, advertising, retargeting, or personalization technology is introduced, this policy will be updated and consent controls will be used where required before non-essential technology activates."] },
      { title: "4. Affiliate destinations", paragraphs: ["When you follow an affiliate or external link, the destination provider or affiliate network may set its own cookies or identifiers to attribute a referral, operate checkout, prevent fraud, or personalize its service. Those technologies are controlled by the destination, not by Fikra in Action. Review its cookie and privacy notices before proceeding."] },
      { title: "5. Essential versus optional technology", paragraphs: ["Essential technology is used only where reasonably necessary to provide, secure, or administer the service. Optional technology is used for analytics, advertising, or personalization that is not strictly required. Where applicable law requires consent, optional technology should not be activated until an appropriate choice has been made."] },
      { title: "6. Managing your browser", paragraphs: ["Most browsers allow you to view, delete, or block cookies and clear site data. Blocking essential storage may prevent administrator sign-in or other secure features from working. Browser controls do not necessarily stop server-side logs, affiliate parameters, or technologies used by a destination after you leave Fikra in Action."] },
      { title: "7. Do Not Track and preference signals", paragraphs: ["Browser Do Not Track signals are not implemented consistently across the industry. We assess legally recognized preference signals where applicable and will update this policy if the site's practices change materially."] },
      { title: "8. Changes to this policy", paragraphs: ["We may update this Cookie Policy when technologies, providers, or legal requirements change. The latest revision date is shown at the top. If a change requires a new consent choice, an appropriate notice or control will be provided where required."] },
      { title: "9. Contact", paragraphs: ["Questions about cookies, storage, or affiliate measurement may be sent to our privacy contact."], links: [{ label: contactEmail, href: `mailto:${contactEmail}?subject=Cookie%20policy%20enquiry` }, { label: "Privacy policy", href: "/privacy" }] },
    ],
  },
};

contentPages["terms-of-service"] = contentPages.terms;
